import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CURL_TOOL } from "../src/lib/runner/external-tools/defs/curl.ts";
import { getToolInstallRoot } from "../src/lib/runner/external-tools/paths.ts";
import { resolveExternalBinary } from "../src/lib/runner/external-tools/resolve-binary.ts";

type Platform = "linux" | "darwin" | "win32";
type Arch = "x64" | "arm64";

function parseTargetArg(argv: string[]): {
  platform: Platform;
  arch: Arch;
  bunTarget?: string;
} {
  const targetArg = argv.find((a) => a.startsWith("--target="));
  if (targetArg) {
    const bunTarget = targetArg.slice("--target=".length);
    const m = bunTarget.match(/^bun-(linux|darwin|windows)-(x64|arm64)/);
    if (m) {
      const platform = (m[1] === "windows" ? "win32" : m[1]) as Platform;
      const arch = m[2] as Arch;
      return { platform, arch, bunTarget };
    }
  }
  return {
    platform: process.platform as Platform,
    arch: process.arch as Arch,
  };
}

const { platform, arch, bunTarget } = parseTargetArg(process.argv.slice(2));
const subdir = `${platform}-${arch}`;
const exe = CURL_TOOL.binaryFileName(platform);

await resolveExternalBinary(CURL_TOOL, {
  allowSystemFallback: false,
  platform,
  arch,
});

const assetImportPath = resolve(join(getToolInstallRoot("curl"), subdir, exe));

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outPath = join(
  scriptDir,
  "..",
  "src",
  "lib",
  "runner",
  "vendored-curl.embed.generated.ts",
);

const content = `// @ts-nocheck — generated; gitignored; import path is machine-specific (see packages/core/scripts/generate-vendored-curl.ts)
// This file is generated by packages/core/scripts/generate-vendored-curl.ts
// It exists to let Bun embed the platform-specific curl binary
// into the single executable produced by \`bun build --compile\` with \`__KULALA_EMBED_CURL__=true\`.

import curlAsset from ${JSON.stringify(assetImportPath)} with { type: "file" };

export async function getVendoredCurl(): Promise<{ bytes: Buffer; filename: string } | null> {
  const bytes = Buffer.from(await Bun.file(curlAsset).arrayBuffer());
  return { bytes, filename: ${JSON.stringify(exe)} };
}
`;

writeFileSync(outPath, content, "utf-8");
console.log(
  `generated ${outPath} for ${subdir}/${exe}${
    bunTarget ? ` (${bunTarget})` : ""
  } from ${assetImportPath}`,
);
