import { writeFileSync } from "node:fs";
import { join } from "node:path";

type Platform = "linux" | "darwin" | "win32";
type Arch = "x64" | "arm64";

function parseTargetArg(argv: string[]): {
  platform: Platform;
  arch: Arch;
  bunTarget?: string;
} {
  const targetArg = argv.find((a) => a.startsWith("--target="));
  if (targetArg) {
    const bunTarget = targetArg.slice("--target=".length);
    // Expected: bun-linux-x64, bun-darwin-arm64, bun-windows-x64, ...
    const m = bunTarget.match(/^bun-(linux|darwin|windows)-(x64|arm64)/);
    if (m) {
      const platform = (m[1] === "windows" ? "win32" : m[1]) as Platform;
      const arch = m[2] as Arch;
      return { platform, arch, bunTarget };
    }
  }
  return {
    platform: process.platform as Platform,
    arch: process.arch as Arch,
  };
}

const { platform, arch, bunTarget } = parseTargetArg(process.argv.slice(2));
const subdir = `${platform}-${arch}`;
const exe = platform === "win32" ? "curl.exe" : "curl";

const assetRelPath = `../../../vendor/curl/${subdir}/${exe}`;
const outPath = join(
  process.cwd(),
  "src",
  "lib",
  "runner",
  "vendored-curl.generated.ts",
);

const content = `// This file is generated by scripts/generate-vendored-curl.ts
// It exists to let Bun embed the platform-specific vendored curl binary
// into the single executable produced by \`bun build --compile\`.

import curlAsset from "${assetRelPath}" with { type: "file" };

export async function getVendoredCurl(): Promise<{ bytes: Buffer; filename: string } | null> {
  const bytes = Buffer.from(await Bun.file(curlAsset).arrayBuffer());
  return { bytes, filename: "${exe}" };
}
`;

writeFileSync(outPath, content, "utf-8");
console.log(
  `generated ${outPath} for ${subdir}/${exe}${bunTarget ? ` (${bunTarget})` : ""}`,
);
