import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

type Platform = "linux" | "darwin" | "win32";
type Arch = "x64" | "arm64";

function parseTargetArg(argv: string[]): {
  platform: Platform;
  arch: Arch;
  bunTarget?: string;
} {
  const targetArg = argv.find((a) => a.startsWith("--target="));
  if (targetArg) {
    const bunTarget = targetArg.slice("--target=".length);
    // Expected: bun-linux-x64, bun-darwin-arm64, bun-windows-x64, ...
    const m = bunTarget.match(/^bun-(linux|darwin|windows)-(x64|arm64)/);
    if (m) {
      const platform = (m[1] === "windows" ? "win32" : m[1]) as Platform;
      const arch = m[2] as Arch;
      return { platform, arch, bunTarget };
    }
  }
  return {
    platform: process.platform as Platform,
    arch: process.arch as Arch,
  };
}

const { platform, arch, bunTarget } = parseTargetArg(process.argv.slice(2));
const subdir = `${platform}-${arch}`;
const exe = platform === "win32" ? "curl.exe" : "curl";

function cacheBaseDir(): string {
  const explicit = process.env.KULALA_CORE_CURL_CACHE_DIR;
  if (explicit) return explicit;

  // Respect XDG on any platform if explicitly set.
  const xdg = process.env.XDG_CACHE_HOME;
  if (xdg) return join(xdg, "kulala");

  if (process.platform === "win32") {
    const localAppData = process.env.LOCALAPPDATA;
    if (localAppData) return join(localAppData, "kulala");
    const appData = process.env.APPDATA;
    if (appData) return join(appData, "kulala");
    const userProfile = process.env.USERPROFILE;
    if (userProfile) return join(userProfile, ".cache", "kulala");
    return join(homedir(), ".cache", "kulala");
  }

  if (process.platform === "darwin") {
    return join(homedir(), "Library", "Caches", "kulala");
  }

  // Linux and other unix-likes.
  return join(homedir(), ".cache", "kulala");
}

function resolveCurlAssetImportPath(): string {
  // Prefer user-writable cached curl (populated by postinstall).
  const cached = join(cacheBaseDir(), "curl", subdir, exe);
  if (existsSync(cached)) return cached;

  // Fallback to repo vendored curl (populated during build/release).
  const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
  const vendored = join(repoRoot, "vendor", "curl", subdir, exe);
  if (existsSync(vendored)) return vendored;

  throw new Error(
    `Missing curl binary for ${subdir}/${exe}. Expected one of:\n` +
      `- ${cached} (run postinstall / scripts/ensure-vendored-curl.ts)\n` +
      `- ${vendored} (populate vendor/curl for releases)\n`,
  );
}

const assetImportPath = resolveCurlAssetImportPath();
const outPath = join(
  join(dirname(fileURLToPath(import.meta.url)), ".."),
  "packages",
  "core",
  "src",
  "lib",
  "runner",
  "vendored-curl.generated.ts",
);

const content = `// @ts-nocheck — generated; import path is machine-specific (see scripts/generate-vendored-curl.ts)
// This file is generated by scripts/generate-vendored-curl.ts
// It exists to let Bun embed the platform-specific vendored curl binary
// into the single executable produced by \`bun build --compile\`.

import curlAsset from "${assetImportPath}" with { type: "file" };

export async function getVendoredCurl(): Promise<{ bytes: Buffer; filename: string } | null> {
  const bytes = Buffer.from(await Bun.file(curlAsset).arrayBuffer());
  return { bytes, filename: "${exe}" };
}
`;

writeFileSync(outPath, content, "utf-8");
console.log(
  `generated ${outPath} for ${subdir}/${exe}${
    bunTarget ? ` (${bunTarget})` : ""
  } from ${assetImportPath}`,
);
