### GRPC_ECHO

# @grpc-import-path grpc/echopb
# @grpc-proto grpc/echopb/echo.proto

GRPC localhost:8080 grpc_echo.v1.EchoService/Echo
Content-Type: application/json

{
  "ping": "Hello, world!"
}

### POSTMAN_GRPC_ECHO

GRPC grpc.postman-echo.com:443 HelloService/SayHello
Content-Type: application/json

{
  "message": "Hello from Kulala!"
}
