@POSTMAN_ECHO_FOO = HelloService/SayHello
@POSTMAN_ECHO_URL = grpc.postman-echo.com:443

### GRPC_ECHO

# @grpc-import-path grpc/echopb
# @grpc-proto grpc/echopb/echo.proto

GRPC localhost:8080 grpc_echo.v1.EchoService/Echo
Content-Type: application/json

{
  "ping": "Hello, world!"
}

### POSTMAN_GRPC_ECHO

# @grpc-plaintext

GRPC {{grpc.addr}}:{{grpc.port}} HelloService/SayHello
Content-Type: application/json

{
  "greeting": "kulala!"
}

### plain

# @grpc-plaintext

GRPC grpcb.in:9000 grpcbin.GRPCBin/Index
HEADER1: {{header1}}

### tls

GRPC grpcb.in:9001 grpcbin.GRPCBin/Index
HEADER1: {{header1}}
