### EXPECT_STATUS_400

// @kulala-expect-status-code 204

GET https://httpbin.org/status/200 HTTP/1.1

### PROMPT_REQUEST

// @kulala-prompt "What is your name?" NAME

GET https://httpbin.org/get?name={{NAME}} HTTP/1.1

### INSECURE_REQUEST_TIMEOUT_REQUEST

// @kulala-curl-insecure
// @timeout 10ms

POST https://httpbin.org/post
  ?someKey=someValue1
  # &someKey2=someValue2
  &someKey3=someValue3
  # &someKey4=someValue4
  &someKey5=someValue5
  # &someKey6=someValue6
  &someKey7=someValue7
  HTTP/1.1
# X-My-Custom-Header1: MyValue1
Content-Type: application/json
X-My-Custom-Header2: MyValue2
# X-My-Custom-Header4: MyValue4
X-My-Custom-Header5: MyValue5
# X-My-Custom-Header6: MyValue6
X-My-Custom-Header7: MyValue7

{
  "username": "user123",
  "password": "pass123"
}

### COOKIE_REQUEST

GET https://httpbin.org/cookies/set/kulala/core HTTP/1.1
Content-Type: application/json

### NO_COOKIE_JAR_REQUEST

// @no-cookie-jar

GET https://httpbin.org/cookies HTTP/1.1
Content-Type: application/json

### COOKIE_JAR_REQUEST

GET https://httpbin.org/cookies HTTP/1.1
Content-Type: application/json

### NO_LOG_REQUEST

// @no-log

POST https://httpbin.org/anything HTTP/1.1
Content-Type: application/json

{
  "username": "user123"
}

### NO_AUTO_ENCODING_REQUEST

// @no-auto-encoding

GET https://httpbin.org/get?
            name=@#$somebody&
            qwerty=%40%23%24
