### KULALA_SHARED

< {%
  request.variables.set("users", [
    { name: "Alice" },
    { name: "Bob" },
  ]);
%}

GET https://echo.kulala.app/get?foobar=1 HTTP/1.1
Content-Type: application/json

### FOO1

< {%
  request.variables.set("users", [
    { name: "Alice" },
    { name: "Bob" },
  ]);
%}

GET https://echo.kulala.app/get?user={{users[*].name}} HTTP/1.1
Content-Type: application/json
X-Header: {{users[*].name}}

### FOO2

GET https://echo.kulala.app/get?user={{users[*].name}} HTTP/1.1
