# @vscode-restclient-compat

### REQUEST_ONE

POST https://httpbin.org/post HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "token": "foobar"
}

### REQUEST_TWO
POST https://httpbin.org/post HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "token": "{{REQUEST_ONE.response.body.$.json.token}}"
}

###

POST https://httpbin.org/post HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "date_header": "{{REQUEST_TWO.response.headers['Date']}}"
}
