name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    environment:
      name: release
      deployment: false
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set version env
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2.2.0

      - name: Set up Node
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Cache Bun
        uses: actions/cache@v5.0.4
        with:
          path: ~/.bun/install/cache
          key: linux-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            linux-bun-${{ hashFiles('**/bun.lock') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Set package version (from tag)
        run: npm --prefix packages/core version "${{ env.VERSION }}" --no-git-tag-version

      - name: Build package
        env:
          KULALA_CORE_BUILD_SKIP_VENDOR_CURL: 1
        run: bun run build
        working-directory: packages/core

      - name: Publish package
        run: npm publish --access public
        working-directory: packages/core

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --generate-notes "${GITHUB_REF_NAME}"
